SHOW DATABASES;

CREATE DATABASE IF NOT EXISTS Bcell_flu_twins_V1_v3;

SHOW DATABASES;

USE Bcell_flu_twins_V1_v3;

SHOW TABLES;

CREATE TABLE IF NOT EXISTS sequences (
    uid BIGINT UNSIGNED NOT NULL,
    uid_work_group_4 TINYINT UNSIGNED NOT NULL,
    uid_work_group_16 TINYINT UNSIGNED NOT NULL,
    uid_work_group_64 TINYINT UNSIGNED NOT NULL,
    uid_work_group_128 TINYINT UNSIGNED NOT NULL,
    uid_work_group_192 TINYINT UNSIGNED NOT NULL,
    uid_work_group_384 SMALLINT UNSIGNED NOT NULL,
    seq_id BIGINT UNSIGNED,
    sequence_string_uid BIGINT UNSIGNED NOT NULL,
    quality_score_uid BIGINT UNSIGNED NOT NULL,
    lineage_uid BIGINT UNSIGNED NOT NULL,
    lineage_uid_work_group_4 TINYINT UNSIGNED NOT NULL,
    lineage_uid_work_group_16 TINYINT UNSIGNED NOT NULL,
    lineage_uid_work_group_64 TINYINT UNSIGNED NOT NULL,
    lineage_uid_work_group_128 TINYINT UNSIGNED NOT NULL,
    lineage_uid_work_group_192 TINYINT UNSIGNED NOT NULL,
    lineage_uid_work_group_384 SMALLINT UNSIGNED NOT NULL,
    patient_uid SMALLINT UNSIGNED,
    patient_str CHAR(24),
    lib_uid INT UNSIGNED,
    clustering_uid INT UNSIGNED,
    year_visit_uid TINYINT UNSIGNED,
    year_visit_str CHAR(24),
    year SMALLINT UNSIGNED,
    visit SMALLINT UNSIGNED,
    V_germline CHAR(48),
    D_germline CHAR(48),
    J_germline CHAR(48),
    V_Evalue DOUBLE,
    D_Evalue DOUBLE,
    J_Evalue DOUBLE,
    isotype ENUM('IgM', 'IgD', 'IgG', 'IgA', 'IgE'),
    subisotype ENUM('IgM', 'IgD', 'IgG1', 'IgG2', 'IgG3', 'IgG4', 'IgA1', 'IgA2', 'IgE', 'IgG', 'IgA'),
    isotype_primer ENUM('IgM', 'IgD', 'IgG', 'IgA', 'IgE', 'no_primer'),
    best_isotype_Evalue DOUBLE,
    best_isotype_score FLOAT,
    second_best_isotype ENUM('IgM', 'IgD', 'IgG1', 'IgG2', 'IgG3', 'IgG4', 'IgA1', 'IgA2', 'IgE', 'IgG', 'IgA'),
    second_best_isotype_Evalue DOUBLE,
    second_best_isotype_score FLOAT,
    isotype_ambiguity FLOAT,
    V_length SMALLINT UNSIGNED,
    D_length SMALLINT UNSIGNED,
    J_length SMALLINT UNSIGNED,
    C_length SMALLINT UNSIGNED,
    fwr1_start SMALLINT UNSIGNED,
    cdr1_start SMALLINT UNSIGNED,
    fwr2_start SMALLINT UNSIGNED,
    cdr2_start SMALLINT UNSIGNED,
    fwr3_start SMALLINT UNSIGNED,
    cdr3_start SMALLINT UNSIGNED,
    cdr3_end SMALLINT UNSIGNED,
    fwr1_length SMALLINT UNSIGNED,
    cdr1_length SMALLINT UNSIGNED,
    fwr2_length SMALLINT UNSIGNED,
    cdr2_length SMALLINT UNSIGNED,
    fwr3_length SMALLINT UNSIGNED,
    cdr3_length SMALLINT UNSIGNED,
    fwr1_AA_start SMALLINT UNSIGNED,
    cdr1_AA_start SMALLINT UNSIGNED,
    fwr2_AA_start SMALLINT UNSIGNED,
    cdr2_AA_start SMALLINT UNSIGNED,
    fwr3_AA_start SMALLINT UNSIGNED,
    cdr3_AA_start SMALLINT UNSIGNED,
    cdr3_AA_end SMALLINT UNSIGNED,
    untemplated_start SMALLINT UNSIGNED,
    untemplated_end SMALLINT UNSIGNED,
    frame ENUM('1', '2', '3'),
    stop_codon BOOL,
    productive BOOL,
    mut_germline_positions VARCHAR(1000),
    mut_germline_before VARCHAR(1000),
    mut_germline_after VARCHAR(1000),
    mut_germline_density FLOAT(8),
    V_germline_identity FLOAT(8),
    abundance SMALLINT UNSIGNED,
    reads_per_molecule CHAR(48),
    more_than_one_read BOOL,
    visits CHAR(16),
    abundances CHAR(24),
    isotypes CHAR(24),
    is_first_visit_seen BOOL,
    mst_ancestor SMALLINT UNSIGNED,
    mst_ancestor_is_germline BOOL,
    mst_ancestor_sequence_uid BIGINT UNSIGNED,
    mst_ancestor_isotype ENUM('IgM', 'IgD', 'IgG1', 'IgG2', 'IgG3', 'IgG4', 'IgA1', 'IgA2', 'IgE', 'IgG', 'IgA'),
    mst_ancestor_uid_seq_str BIGINT UNSIGNED,
    mst_dist_to_ancestor SMALLINT UNSIGNED,
    mst_steps_to_root SMALLINT UNSIGNED,
    mst_dist_to_root SMALLINT UNSIGNED,
    mst_steps_to_root_normalized FLOAT(16) UNSIGNED,
    mst_dist_to_root_normalized FLOAT(16) UNSIGNED,
    mst_num_descendants SMALLINT UNSIGNED,
    mst_centrality FLOAT(16) UNSIGNED,
    mst_no_isotype_constraint_ancestor SMALLINT UNSIGNED,
    mst_no_isotype_constraint_ancestor_is_germline BOOL,
    mst_no_isotype_constraint_ancestor_sequence_uid BIGINT UNSIGNED,
    mst_no_isotype_constraint_ancestor_isotype ENUM('IgM', 'IgD', 'IgG1', 'IgG2', 'IgG3', 'IgG4', 'IgA1', 'IgA2', 'IgE', 'IgG', 'IgA'),
    mst_no_isotype_constraint_ancestor_uid_seq_str BIGINT UNSIGNED,
    mst_no_isotype_constraint_dist_to_ancestor SMALLINT UNSIGNED,
    mst_no_isotype_constraint_steps_to_root SMALLINT UNSIGNED,
    mst_no_isotype_constraint_dist_to_root SMALLINT UNSIGNED,
    mst_no_isotype_constraint_steps_to_root_normalized FLOAT(16) UNSIGNED,
    mst_no_isotype_constraint_dist_to_root_normalized FLOAT(16) UNSIGNED,
    mst_no_isotype_constraint_num_descendants SMALLINT UNSIGNED,
    mst_no_isotype_constraint_centrality FLOAT(16) UNSIGNED,
    datetime_created TIMESTAMP DEFAULT 0,
    datetime_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY ( uid ),
    INDEX ( patient_uid, clustering_uid, lineage_uid_work_group_64 ),
    INDEX ( patient_uid, clustering_uid, lineage_uid_work_group_192 ),
    INDEX ( patient_uid, clustering_uid, lineage_uid_work_group_384 ),
    INDEX ( lineage_uid_work_group_64 ),
    INDEX ( lineage_uid_work_group_192 ),
    INDEX ( lineage_uid_work_group_384 ),
    INDEX ( uid_work_group_64 ),
    INDEX ( uid_work_group_192 ),
    INDEX ( uid_work_group_384 ),
    INDEX ( mst_ancestor_isotype ),
    INDEX ( mst_no_isotype_constraint_ancestor_isotype )
);

CREATE TABLE IF NOT EXISTS sequence_strings (
  uid BIGINT UNSIGNED NOT NULL,
  seq_id BIGINT UNSIGNED,
  patient_uid SMALLINT UNSIGNED,
  lib_uid INT UNSIGNED,
  V_seq VARCHAR(1000),
  D_seq CHAR(255),
  J_seq CHAR(255),
  C_seq CHAR(255),
  leader_seq CHAR(255),
  AA CHAR(255),
  PRIMARY KEY ( uid )
);

CREATE TABLE IF NOT EXISTS quality_scores (
  uid BIGINT UNSIGNED NOT NULL,
  seq_id BIGINT UNSIGNED,
  patient_uid SMALLINT UNSIGNED,
  lib_uid INT UNSIGNED,
  quality_scores MEDIUMTEXT,
  PRIMARY KEY ( uid )
);

CREATE TABLE IF NOT EXISTS sequence_features (
  seq_id BIGINT UNSIGNED NOT NULL,
  name CHAR(255),
  value CHAR(255),
  uid BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY ( uid )
);

CREATE TABLE IF NOT EXISTS lineages (
    uid BIGINT UNSIGNED NOT NULL,
    uid_work_group_4 TINYINT UNSIGNED NOT NULL,
    uid_work_group_16 TINYINT UNSIGNED NOT NULL,
    uid_work_group_64 TINYINT UNSIGNED NOT NULL,
    uid_work_group_128 TINYINT UNSIGNED NOT NULL,
    uid_work_group_192 TINYINT UNSIGNED NOT NULL,
    uid_work_group_384 SMALLINT UNSIGNED NOT NULL,
    patient_uid SMALLINT UNSIGNED,
    clustering_uid INT UNSIGNED NOT NULL,
    subsample_p FLOAT(8),
    subsample_replicate SMALLINT UNSIGNED,
    path CHAR(255),
    num_unique_seqs MEDIUMINT UNSIGNED,
    abundance MEDIUMINT UNSIGNED,
    num_IgM MEDIUMINT UNSIGNED,
    num_IgD MEDIUMINT UNSIGNED,
    num_IgG MEDIUMINT UNSIGNED,
    num_IgA MEDIUMINT UNSIGNED,
    num_IgE MEDIUMINT UNSIGNED,
    frac_IgM FLOAT(16) UNSIGNED,
    frac_IgD FLOAT(16) UNSIGNED,
    frac_IgG FLOAT(16) UNSIGNED,
    frac_IgA FLOAT(16) UNSIGNED,
    frac_IgE FLOAT(16) UNSIGNED,
    num_IgG1 MEDIUMINT UNSIGNED,
    num_IgG2 MEDIUMINT UNSIGNED,
    num_IgG3 MEDIUMINT UNSIGNED,
    num_IgG4 MEDIUMINT UNSIGNED,
    num_IgA1 MEDIUMINT UNSIGNED,
    num_IgA2 MEDIUMINT UNSIGNED,
    frac_IgG1 FLOAT(16) UNSIGNED,
    frac_IgG2 FLOAT(16) UNSIGNED,
    frac_IgG3 FLOAT(16) UNSIGNED,
    frac_IgG4 FLOAT(16) UNSIGNED,
    frac_IgA1 FLOAT(16) UNSIGNED,
    frac_IgA2 FLOAT(16) UNSIGNED,
    gini_abundance FLOAT(16) UNSIGNED,
    mst BOOL NOT NULL DEFAULT 0,
    mst_no_isotype_constraint BOOL NOT NULL DEFAULT 0,
    alignment BOOL NOT NULL DEFAULT 0,
    tree BOOL NOT NULL DEFAULT 0,
    tree_pdf BOOL NOT NULL DEFAULT 0,
    sfs BOOL NOT NULL DEFAULT 0,
    mst_max_centrality FLOAT(16) UNSIGNED,
    mst_num_descendants_from_germline SMALLINT UNSIGNED,
    mst_no_isotype_constraint_max_centrality FLOAT(16) UNSIGNED,
    mst_no_isotype_constraint_num_descendants_from_germline SMALLINT UNSIGNED,
    datetime_created TIMESTAMP DEFAULT 0,
    datetime_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY ( uid ),
    INDEX ( patient_uid, clustering_uid, uid_work_group_64 ),
    INDEX ( patient_uid, clustering_uid, uid_work_group_192 ),
    INDEX ( patient_uid, clustering_uid, uid_work_group_384 ),
    INDEX ( uid_work_group_64, mst, subsample_p ),
    INDEX ( uid_work_group_192, mst, subsample_p ),
    INDEX ( uid_work_group_384, mst, subsample_p )
);

CREATE TABLE IF NOT EXISTS lineage_features (
  lineage_id BIGINT UNSIGNED NOT NULL,
  name CHAR(255),
  value CHAR(255),
  uid BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY ( uid )
);

CREATE TABLE IF NOT EXISTS patients (
    uid SMALLINT UNSIGNED NOT NULL,
    name CHAR(24),
    full_name CHAR(48),
    gender ENUM('male', 'female', 'other'),
    age_at_consent FLOAT(8) UNSIGNED,
    ethnicity CHAR(200),
    race CHAR(200),
    race_other CHAR(200),
    twin_status ENUM('twin', 'non-twin'),
    twin_sibling CHAR(200),
    self_zygosity ENUM('fraternal', 'identical'),
    zygosity_assay_result CHAR(200),
    notes VARCHAR(1000),
    PRIMARY KEY ( uid )
);

CREATE TABLE IF NOT EXISTS libs (
    uid INT UNSIGNED NOT NULL,
    patient_uid SMALLINT UNSIGNED,
    patient_name CHAR(24),
    year_visit_uid TINYINT UNSIGNED,
    year_visit_str CHAR(24),
    original_igh_pipeline_output VARCHAR(1000),
    subsampled_igh_pipeline_output VARCHAR(1000),
    subsample_p FLOAT(8),
    original_num_seqs INT UNSIGNED,
    target_num_seqs FLOAT(16),
    num_seqs INT UNSIGNED,
    subsample_replicate SMALLINT UNSIGNED,
    PRIMARY KEY ( uid )
);

CREATE TABLE IF NOT EXISTS clusterings (
    uid INT UNSIGNED NOT NULL,
    patient_uid SMALLINT UNSIGNED,
    subsample_p FLOAT(8),
    subsample_replicate SMALLINT UNSIGNED,
    original_num_seqs INT UNSIGNED,
    target_num_seqs INT UNSIGNED,
    num_seqs INT UNSIGNED,
    clustering_method CHAR(255),
    clustering_CDR3_similarity_cutoff FLOAT(8),
    clustering_VDJ_similarity_cutoff FLOAT(8),
    clustering_templated_similarity_cutoff FLOAT(8),
    clustering_Q_cutoff TINYINT UNSIGNED,
    clustering_V_allele_collapse_dict_file VARCHAR(1000),
    PRIMARY KEY ( uid )
);

SHOW TABLES;

